CREATE TABLE clients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_number INTEGER ,
    street varchar,
    client_name varchar,
    post_cod INTEGER  NULL,
    bottle_type varchar,
    date_deliver TIMESTAMP,
    observations varchar NULL,
    delivered boolean 
)
